//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temu_Wordle_Solver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Temu_Wordle_Solver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aahed
        ///aalii
        ///aapas
        ///aargh
        ///aarti
        ///abaca
        ///abaci
        ///aback
        ///abacs
        ///abaft
        ///abaht
        ///abaka
        ///abamp
        ///aband
        ///abase
        ///abash
        ///abask
        ///abate
        ///abaya
        ///abbas
        ///abbed
        ///abbes
        ///abbey
        ///abbot
        ///abcee
        ///abeam
        ///abear
        ///abeat
        ///abeer
        ///abele
        ///abeng
        ///abers
        ///abets
        ///abeys
        ///abhor
        ///abide
        ///abies
        ///abius
        ///abjad
        ///abjud
        ///abled
        ///abler
        ///ables
        ///ablet
        ///ablow
        ///abmho
        ///abnet
        ///abode
        ///abohm
        ///aboil
        ///aboma
        ///aboon
        ///abord
        ///abore
        ///aborn
        ///abort
        ///about
        ///above
        ///abram
        ///abray
        ///abrim
        ///abrin
        ///abris
        ///absey
        ///absit
        ///abuna
        ///abune
        ///abura
        ///aburn
        ///abuse
        ///abuts
        ///abuzz
        ///abyes
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordList {
            get {
                return ResourceManager.GetString("WordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which
        ///there
        ///their
        ///about
        ///would
        ///these
        ///other
        ///words
        ///could
        ///write
        ///first
        ///water
        ///after
        ///where
        ///right
        ///think
        ///three
        ///years
        ///place
        ///sound
        ///great
        ///again
        ///still
        ///every
        ///small
        ///found
        ///those
        ///never
        ///under
        ///might
        ///while
        ///house
        ///world
        ///below
        ///asked
        ///going
        ///large
        ///until
        ///along
        ///shall
        ///being
        ///often
        ///earth
        ///began
        ///since
        ///study
        ///night
        ///light
        ///above
        ///paper
        ///parts
        ///young
        ///story
        ///point
        ///times
        ///heard
        ///whole
        ///white
        ///given
        ///means
        ///music
        ///miles
        ///thing
        ///today
        ///later
        ///using
        ///money
        ///lines
        ///order
        ///group
        ///among
        ///learn
        ///known
        ///s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
